### ISSUE TITLE
OptimizeNotCalled()

### ISSUE THREAD

**Issue by kalmarek** [mariohsouto/ProxSDP.jl#40] opened 2019-04-18 16:31 UTC
After solving a problem:

```julia
SDPproblem = # defined through JuMP 
with_ProxSDP = with_optimizer(ProxSDP.Optimizer, tol_primal=1e-10, tol_dual=1e-10, log_verbose=true)
optimize!(SDPproblem, with_ProxSDP)
```

```
...
----------------------------------------------------------------------
 ProxSDP failed to converge in 70.66 seconds
 Primal objective = -0.0
 Dual objective = 0.00026
 Duality gap (%) = 3.133284148680549e13 %
======================================================================
```
```julia
objective_value(SDPproblem)
OptimizeNotCalled()
...
```
Additional info:
It is a SDP problem which should (for theoretical reasons) have a low-rank solution; 
As I define it, it's a feasibility problem, but I add a dummy optimization variable to maximize and bound it by 0.0 from above.

**Comment by guilhermebodin** [comment] 2019-04-23 17:41
Could you provide us the problem? If the problem is that the termination status is OptimizeNotCalled this should be fixed by #25 which will be available in future releases

**Closed** 2019-06-11 20:03 UTC
